### ISSUE TITLE
CMake: "No project() command is present."

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/extract-xiso#31]
I get this warning when building nxdk from scratch:

> CMake Warning (dev) in CMakeLists.txt:
>   No project() command is present.  The top-level CMakeLists.txt file must
>   contain a literal, direct call to the project() command.  Add a line of
>   code such as
> 
>     project(ProjectName)
> 
>   near the top of the file, but after cmake_minimum_required().
> 
>   CMake is pretending there is a "project(Project)" command on the first
>   line.
> This warning is for project developers.  Use -Wno-dev to suppress it.
>

**Comment by per1234** [comment]
`project()` call was added in https://github.com/XboxDev/extract-xiso/pull/35.
