### ISSUE TITLE
Windows build of 2.7.1

### ISSUE THREAD

**Issue by Natetronn** [XboxDev/extract-xiso#42]
Is there a Windows build for 2.7.1? The Appveyor links here in the repo readme are pointing to v2.5, as well as the downloads on Source Forge.

**Comment by Natetronn** [comment]
Hmm, I see you may have an updated Python 3 version? Would it be best to use that instead at this point?

**Comment by thrimbor** [comment]
The AppVeyor link points to the latest build from two months ago.

**Comment by Natetronn** [comment]
Hmm weird, I guess it does. Not sure why I was getting the v2.5 for some reason.
