### ISSUE TITLE
"Click Here Latest Windows Build" link broken

### ISSUE THREAD

**Issue by Avishadur** [XboxDev/extract-xiso#57]
When you click the link in your readme, it takes you to a page that just says 
`{"message":"Artifact not found or access denied."}`
It's probably minor; but it saves trying to compile for ourselves

**Comment by simi** [comment]
You can download stuff on GitHub Actions meanwhile.

For example here: https://github.com/XboxDev/extract-xiso/actions/runs/939299778.

**Comment by ryandeering** [comment]
> You can download stuff on GitHub Actions meanwhile.
> 
> For example here: https://github.com/XboxDev/extract-xiso/actions/runs/939299778.

Says for me the links have expired.

**Comment by requeijaum** [comment]
The artifacts are expiring quickly. Can anyone upload a Windows x86 version?
I'm using v2.5 from SourceForge and it's pure suffering.

**Comment by simi** [comment]
@requeijaum feel free to try my build - https://files.ofpisnotdead.com/files/xbox/extract-xiso.exe.

**Comment by GXTX** [comment]
Actions are setup to create a release when things are pushed to master. See the sidebar for "Releases", and consider closing this issue.
