### ISSUE TITLE
[Windows v2.7.1] open error: -d No such file or directory

### ISSUE THREAD

**Issue by Forusim** [XboxDev/extract-xiso#71]
Hello,
I am trying to figure out, how to properly rewrite into a specific directory:
`extract-xiso.exe -r "D:\Temp\game.iso" -d "D:\Games\Xbox"`
This will write into the source directory "D:\Temp" and gives following error at the end:
`open error: -d No such file or directory`
In the help it is said, but something is missing here:
```
-d <directory>      In extract mode, expand xiso in <directory>.
                    In rewrite mode, rewrite xiso in <directory>.
```
Any hint is appreciated.

**Comment by 0ddb0d** [comment]
Your parameters are in the wrong order, -d is an option, it needs to come before the mode, like this:
> extract-xiso.exe -d "D:\Games\Xbox" -r "D:\Temp\game.iso"
Also note that the directory must already exist.
