### ISSUE TITLE
extract-xiso can fail to list or extract certain files in rare cases

### ISSUE THREAD

**Issue by gaasedelen** [XboxDev/extract-xiso#76]
I have been vetting extract-xiso (32, and 64bit builds) on linux against xbfuse. I extract the redump ISO using each tool to separate directories, and then sha1 all files in the extractions.

But it appears that extract-xiso fails to see and extract a certain file from the following redump ISO:

```
Loaded 2581 REDUMP ISO hashes
--------------------------------------------------
 -    FILE PATH: /volume1/software/xbox/games/redump/100 Best Xbox Games Game Disc, The (UK).iso
 -    FILE SHA1: 5d1d8ddfb2c4a48eab5253bbb0888637f60efe30
 -  REDUMP NAME: 100 Best Xbox Games Game Disc, The (UK)
 - - - - - - - - - - - - - - - - - - - -
 - RUNNING extract_xbfuse(...)
 - MOUNTING...
 - COPYING FILES...
 - UNMOUNTING...
 - HASHING FILES...
 - EXTRACTION DONE!
 - - - - - - - - - - - - - - - - - - - -
 - RUNNING extract_xiso_32(...)
 - HASHING FILES...
 - EXTRACTION DONE!
 - - - - - - - - - - - - - - - - - - - -
 - RUNNING extract_xiso_64(...)
 - HASHING FILES...
 - EXTRACTION DONE!
 - COMPARING ALL HASHES...
 ---- extract_xbfuse vs extract_xiso_32
!!! HASH FILE COMPARISON FAILED BETWEEN extract_xbfuse AND extract_xiso_32 !!!
```

Specifically, xbfuse produced one extra file from the ISO that extract-xiso did not:

```
5d7cdd950e87b5feaad5072037560f860b302da0  Quantum/data/frontend/savebar/model.cmm
```

Based on visual inspection of the file in a hex editor, I do believe this is a real file that extract-xiso has missed. I also tried the 32 bit windows release build of extract-xiso on github and it does not list the file either:

[listing.txt](https://github.com/XboxDev/extract-xiso/files/10842250/listing.txt)

Here are the sha1 hash listings which again show the file missing file between the two tools:

[sha1_extract_xiso.txt](https://github.com/XboxDev/extract-xiso/files/10842253/sha1_extract_xiso.txt)
[sha1_xbfuse.txt](https://github.com/XboxDev/extract-xiso/files/10842257/sha1_xbfuse.txt)

I am not sure when I will find the time to dig into this specific case, but I hope that this issue might pique someone's curiosity, seems like a fun little bug to track down.

**Comment by rapperskull** [comment]
This happens because that file is in sector 0, that extract-iso treats as invalid.
