### ISSUE TITLE
[Suggestion] Linux support

### ISSUE THREAD

**Issue by MesaBlack** [XboxDev/extract-xiso#82]
This includes debian instructions, debian building, and flatpak.

**Comment by ExoSkye** [comment]
For one, building this is as simple as building it with CMake, two, given the glaring issues in `extract-xiso`, I doubt it'll ever be "properly" packaged until those issues are fixed, and even then, the chance of it being `flatpak` packaged are basically 0 given that it's a simple console app, not a bigger app

(btw I'm not a maintainer in XboxDev, although I have contributed in the past, so these are my opinions only, not the opinions of XboxDev as a whole)

**Comment by MesaBlack** [comment]
where can I find cmake?

**Comment by ExoSkye** [comment]
since i presume you're on debian
`sudo apt install cmake`

**Comment by mborgerson** [comment]
Linux build instructions already provided. Maybe a statically linked binary will be published one day, but deb/flatpak are unlikely

**Comment by MesaBlack** [comment]
abandoning due to internal and personal disputes.

**Comment by jirikrepl** [comment]
It's like 4 C source files. I guess if you install gcc compiler on the command line in Linux/Mac. Or with the help of some C/C++ IDE.

    $ cmake .

    $ make

I was able to compile.
