### ISSUE TITLE
I am trying to run the program but I keep getting command not found. ubuntu

### ISSUE THREAD

**Issue by F3arM3** [XboxDev/extract-xiso#88]
even if I open the folder in the terminal and copy paste the program name it still says command not found

here is a text file copy of my terminal if it helps
[extract xiso.txt](https://github.com/XboxDev/extract-xiso/files/13541804/extract.xiso.txt)

**Comment by thrimbor** [comment]
You're missing the obligatory `./` to run executables outside of $PATH. Check the readme for examples.

Also, this is a bugtracker.
